---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt: 
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install pip
  ansible.builtin.apt:
    name: pip
    state: latest

- name: Install Docker Module for Python
  ansible.builtin.apt:
    name: mysql-client

####  "Install mysql client" mais pour l'instant on installe docker ? Tu pourras m'expliquer demain stp ?

- name: Install mysql-client to check db
  ansible.builtin.pip:
    name: docker
