# APACHE DOCKERFILE

FROM httpd:latest

EXPOSE 80 443

COPY httpd.conf /usr/local/apache2/conf/httpd.conf

RUN mkdir -p /usr/local/apache2/conf/sites
COPY anyastu.conf /usr/local/apache2/conf/sites/anyastu.conf

#COPY ./web_pages/* /usr/share/nginx/html/
#COPY ./default.conf /etc/nginx/conf.d/default.conf

#CMD ["httpd", "-D", "FOREGROUND;"]
