--- 
- name: Installing the prerequisites on the server
  vars_files:
    - group_vars/all_vps
    # - group_vars/all_local
  gather_facts: no
  hosts: "{{ host }}"
#  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  roles:
    - install


- name: Create docker volume
  vars_files:
    - group_vars/all_vps
    # - group_vars/all_local
  hosts: "{{ host }}"
  gather_facts: no
#  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  tasks:
    - name: Create and name the Docker Volume
      community.docker.docker_volume:
        volume_name: db_volume


- name: Deploy the MariaDB container on the server
  vars_files:
    - group_vars/all_vps
    # - group_vars/all_local
  gather_facts: no
  hosts: "{{host}}"
#  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  roles:
    - mariadb


- name: Deploy the phpMyAdmin container on the server
  vars_files:
    - group_vars/all_vps
    # - group_vars/all_local
  gather_facts: no
  hosts: "{{host}}"
#  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  roles:
    - phpmyadmin


- name: Deploy the Wordpress container on the server
  vars_files:
    - group_vars/all_vps
    # - group_vars/all_local
  gather_facts: no
  hosts: "{{host}}"
#  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  roles:
    - wordpress
