--- 
- name: Installing the prerequisites on the server
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{ host }}"
  become: yes
  become_method: sudo
  roles:
    - install

- name: Setup the Docker environment on the server
  vars_files:
     - group_vars/all
  hosts: "{{ host }}"
  gather_facts: no
#  become: yes
#  become_method: sudo
  roles:
    - docker_setup

- name: Deploy the MariaDB container on the server
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{host}}"
#  become: yes
#  become_method: sudo
  roles:
    - mariadb


- name: Deploy the phpMyAdmin container on the server
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{host}}"
#  become: yes
#  become_method: sudo
  roles:
    - phpmyadmin


- name: Deploy the Wordpress container on the server
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{host}}"
#  become: yes
#  become_method: sudo
  roles:
    - wordpress
