--- 
- name: Installing the prerequisites on the server
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{ host }}"
  become: yes
  become_method: sudo
  tags:
    - prerequisites
  roles:
    - 01-install

- name: Setup the Docker environment on the server
  vars_files:
     - group_vars/all
  hosts: "{{ host }}"
  gather_facts: no
  become: yes
  become_method: sudo
  tags:
    - starting_docker
  roles:
    - 02-docker_setup

- name: Deploy the MariaDB container on the server
  vars_files:
     - group_vars/all
     - group_vars/vault
  gather_facts: no
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tags:
    - database
  roles:
    - 03-mariadb

- name: Deploy the phpMyAdmin container on the server
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tags:
    - pma
  roles:
    - 04-phpmyadmin

- name: Deploy the Wordpress container on the server
  vars_files:
     - group_vars/all
     - group_vars/vault
  gather_facts: no
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tags:
    - website
  roles:
    - 05-wordpress

- name: Deploy the Apache container on the server
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tags:
    - proxy
  roles:
    - 06-apache

- name: Download the deleting script on the VPS
  vars_files:
     - group_vars/all
  gather_facts: no
  hosts: "{{host}}"
  tags:
    - deleting
  roles:
    - 10-deleting
