---
- name: Install docker and daemons
  hosts: anyastu
  become: true
  roles:
    - role: install

- name: Create docker Network
  hosts: anyastu
  become: true
  tasks:
    - name: Create and name the Docker Network  # automatically created
                                                # we just do it for clarity purposes
      community.docker.docker_network:
        name: "cloud-1_network"
        # driver: overlay # default is bridge and works for the subject's purposes

- name: Create docker volume
  hosts: anyastu
  become: true
  tasks:
    - name: Create and name the Docker Volume
      community.docker.docker_volume:
        volume_name: db_volume

- name: Build and run nginx
  hosts: anyastu
  become: true
  roles:
    - role: nginx

- name: Build and run phpmyadmin
  hosts: anyastu
  become: true
  roles:
    - role: phpmyadmin

- name: Build and run mariadb
  hosts: anyastu
  become: true
  roles:
    - role: mariadb

- name: Build and run wordpress
  hosts: anyastu
  become: true
  roles:
    - role: wordpress
