- name: Create the main directory
  file:
    path: "{{ ssl_cert_path }}"
    state: directory

- name: Copy the basic configuration files on the server
  copy:
    src: httpd.conf
    dest: "{{ httpd_dir }}/httpd.conf"
    #directory_mode: yes

- name: Copy the Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ httpd_dir }}/Dockerfile"

#- name: Create the certificates folder
#  file:
#    path: "{{ httpd_path }}"
#    state: directory

- name: Copy the adapted Virtual Host configuration site on the server - With Domain name
  template:
    src: domain_website.conf.j2
    dest: "{{ httpd_dir }}/website.conf"
  when: domain == "yes"

- name: Copy the adapted Virtual Host configuration site on the server - Without Domain Name
  template:
    src: basic_website.conf.j2
    dest: "{{ httpd_dir }}/website.conf"
  when: domain == "no"

- name: Build the image
  community.docker.docker_image:
    name: "{{ httpd_image }}"
    state: present
    source: build
    build:
      path: "{{ httpd_dir }}"

- name: Run the container
  community.docker.docker_container:
    name: "{{ httpd_name }}"
    image: "{{ httpd_image }}"
    state: started
    restart: yes
    restart_policy: always
    networks:
      - name: "{{network_name}}"
    ports:
      - "80:80"
      - "443:443"
    container_default_behavior: compatibility
