- name: Creates {service}_build directory
  ansible.builtin.file:
    path: ~/mariadb_build
    state: directory
    mode: '755'

- name: Copy Dockerfile
  ansible.builtin.template:
    src: Dockerfile
    dest: mariadb_build/Dockerfile

- name: Copy .conf
  ansible.builtin.template:
    src: mariadb.conf
    dest: mariadb_build/mariadb.conf

- name: build image
  community.docker.docker_image:
    name: mariadb_img
    state: present
    build:
      path: mariadb_build

- name: run container
  community.docker.docker_container:
    name: mariadb_container
    image: mariadb_img
    state: present
    networks:
      name: "{{network_name}}"
    restart_policy: "on-failure"
    restart_retries: 3
