#   php:
#    image: php:7.2-fpm
#    volumes:
#      - /var/www/docker-study.loc/recipe-03/php:/var/www/myapp
#      - /var/www/docker-study.loc/recipe-03/docker/php.ini:/usr/local/etc/php/php.ini
#    depends_on:
#      - mariadb