---
- name: Run temporary nginx container
  community.docker.docker_container:
    name: temp_nginx
    image: nginx:latest
    state: started
    ports:
    - 80:80
    - 443:443
    restart: no
    volumes:
      - ./certif/:/etc/nginx/ssl/:rw


- name: Generate SSL certificate
  community.docker.docker_container:
    name: certbot_container
    image: certbot/certbot:latest
    state: started
    command: certbot certonly --webroot -w /var/www/nginx -d anyastu.fr
    restart: no
    volumes:
      - ./certif/:/etc/letsencrypt/:rw

# maybe should wait for the end of the certif creation ?
# https://mindsers.blog/fr/post/configurer-https-nginx-docker-lets-encrypt/

- name: Stop temporaray nginx container
  community.docker.docker_container:
    name: temp_nginx
    state: absent
