- name: Create the directory
  file:
    path: "{{ wp_path }}"
    state: directory

- name: Copy the Dockerfile
  template:
    src: Dockerfile
    dest: "{{ wp_dir }}/Dockerfile"

#- name: Copy the configuration file
#  template:
#    src: default.conf
#    dest: wordpress_build/wordpress.conf

- name: Build the image
  community.docker.docker_image:
    name: "{{ wp_image }}"
    state: present
    source: build
    build:
      path: "{{ wp_dir }}"


- name: Run the container
  community.docker.docker_container:
    name: "{{ wp_name }}"
    image: "{{ wp_image }}"
    state: started
    restart: yes
    restart_policy: always
    networks:
      - name: "{{network_name}}"
    ports:
      - "9000:80"
    container_default_behavior: compatibility
