- name: Creates directory
  file:
    path: "{{ db_path }}"
    state: directory

- name: Copy Dockerfile
  template:
    src: Dockerfile
    dest: "{{ db_dir }}/Dockerfile"

- name: Copy .conf
  template:
    src: mariadb.conf
    dest: "{{ db_dir }}/mariadb.conf"

- name: Build image
  community.docker.docker_image:
    name: "{{ db_image }}"
    state: present
    source: build
    build:
      path: "{{ db_dir }}"

- name: Run container
  community.docker.docker_container:
    name: "{{ db_name }}"
    image: "{{ db_image }}"
    state: started
    restart: yes
    restart_policy: always
    networks:
      - name: "{{network_name}}"
    container_default_behavior: compatibility
