- name: Creates pma_build directory
  file:
    path: "{{ pma_directory }}"
    state: directory

- name: Copy Dockerfile
  template:
    src: Dockerfile
    dest: pma_build/Dockerfile

# - name: Copy .conf
#   template:
#     src: pma.conf
#     dest: pma_build/pma.conf

- name: build image
  community.docker.docker_image:
    name: pma_img
    state: present
    source: build
    build:
      path: pma_build

- name: run container
  community.docker.docker_container:
    name: pma_container
    image: pma_img
    state: started
    restart: yes
    restart_policy: always
    networks:
      - name: "{{network_name}}"
    ports:
      - "8080:80"
    container_default_behavior: compatibility
