# APACHE DOCKERFILE

FROM httpd:latest

EXPOSE 80 443

RUN mkdir -p /usr/local/apache2/conf/sites
RUN mkdir -p "/usr/local/apache2/conf/ssl/certificates"

COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY website.conf /usr/local/apache2/conf/sites/website.conf

COPY "certificates" "/usr/local/apache2/conf/ssl/certificates"
