#  web:
#    image: nginx:1.17
#    ports:
#      - 80:80
#    volumes:
#      - /var/www/docker-study.loc/recipe-03/php:/var/www/myapp
#      - /var/www/docker-study.loc/recipe-03/docker/site.conf:/etc/nginx/conf.d/site.conf
#    depends_on:
#      - php
#      - mariadb

FROM httpd:latest

EXPOSE 80 443

#COPY ./web_pages/* /usr/share/nginx/html/
#COPY ./default.conf /etc/nginx/conf.d/default.conf

#CMD ["nginx", "-g", "daemon off;"]
